# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RunDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddata',
            old_name='time_to_runn',
            new_name='time_to_runnnnn',
        ),
    ]
