# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RunDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='fooddata',
            name='caloriesPerServing',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='fooddata',
            name='servingSize',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='fooddata',
            name='totalCalories',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default=True, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitnessLevel',
            field=models.IntegerField(choices=[(1, 'Novice'), (2, 'Average'), (3, 'Athletic')], default=True),
        ),
    ]
