# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunDoApp', '0004_fooddata_foodname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddata',
            old_name='caloriesPerServing',
            new_name='calories',
        ),
        migrations.RemoveField(
            model_name='fooddata',
            name='totalCalories',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(max_length=30),
        ),
    ]
