# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunDoApp', '0005_auto_20171218_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddata',
            old_name='servingSize',
            new_name='userServings',
        ),
        migrations.AddField(
            model_name='fooddata',
            name='servingUnits',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
