# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunDoApp', '0006_auto_20171219_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddata',
            name='calories',
        ),
        migrations.AddField(
            model_name='fooddata',
            name='servingCalories',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddata',
            name='servingSize',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddata',
            name='totalCalories',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='userServings',
            field=models.FloatField(),
        ),
    ]
