# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RunDoApp', '0007_auto_20171219_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddata',
            old_name='foodName',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='fooddata',
            old_name='servingCalories',
            new_name='serving_calories',
        ),
        migrations.RenameField(
            model_name='fooddata',
            old_name='servingSize',
            new_name='serving_size',
        ),
        migrations.RenameField(
            model_name='fooddata',
            old_name='servingUnits',
            new_name='serving_units',
        ),
        migrations.RenameField(
            model_name='fooddata',
            old_name='totalCalories',
            new_name='total_calories',
        ),
        migrations.RenameField(
            model_name='fooddata',
            old_name='userServings',
            new_name='user_servings',
        ),
    ]
